"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
type Root = { id:string; label:string; enabled:boolean }; type Hit = { id:string; path:string; rootId:string; rootLabel:string; fileName:string; size:number; width:number|null; height:number|null; estimate:string; duplicate:boolean; similarity:number|null; match:string };
export default function ImageSearchPage(){
 const [model,setModel]=useState("wb011852"),[photo,setPhoto]=useState<File|null>(null),[roots,setRoots]=useState<Root[]>([]),[hits,setHits]=useState<Hit[]>([]),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Record<string,boolean>>({}),[message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/image-search").then(r=>r.json()).then(d=>setRoots(d.roots||[]));},[]);
 async function search(){setBusy(true);setMessage("로컬 인덱스를 갱신하고 검색 중입니다…");try{const r=await fetch("/api/image-search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model,rootIds:roots.filter(x=>x.enabled).map(x=>x.id)})});const d=await r.json();if(!r.ok)throw Error(d.error);setHits(d.hits||[]);setSelected(Object.fromEntries((d.hits||[]).map((x:Hit)=>[x.id,true])));setMessage(`${d.hits?.length||0}장 발견. 이동·삭제는 실행하지 않았습니다.`);}catch(e){setMessage(e instanceof Error?e.message:"검색 실패");}finally{setBusy(false);}}
 const chosen=hits.filter(x=>selected[x.id]); const count=(id:string)=>hits.filter(x=>x.rootId===id).length; const dup=hits.filter(x=>x.duplicate).length;
 return <main style={{maxWidth:1280,margin:"0 auto",padding:"36px 24px",fontFamily:"Pretendard, sans-serif",color:"#29231f"}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"end",marginBottom:24}}><div><small style={{color:"#986f55",letterSpacing:2}}>NOID-B OS · IMAGE</small><h1 style={{fontSize:42,margin:"8px 0"}}>제품사진 통합검색</h1><p>모델명과 대표사진으로 PC·MYBOX·Google Drive의 제품사진을 찾아 미리봅니다.</p></div><Link href="/image-generator">이미지 생성기로 돌아가기</Link></header>
 <section style={{border:"1px solid #e4ddd7",borderRadius:14,padding:22,background:"#fff"}}><div style={{display:"flex",gap:12,alignItems:"end",flexWrap:"wrap"}}><label>모델명<input value={model} onChange={e=>setModel(e.target.value)} placeholder="예: wb011852" style={{display:"block",padding:11,marginTop:6,border:"1px solid #d8cec6",borderRadius:8}}/></label><label>대표사진<input type="file" accept="image/*" onChange={e=>setPhoto(e.target.files?.[0]||null)} style={{display:"block",marginTop:12}}/></label><button onClick={search} disabled={busy||!model.trim()} style={{padding:"11px 18px",background:"#8e644c",color:"#fff",border:0,borderRadius:8}}>{busy?"검색 중…":"관련 이미지 찾기"}</button></div><div style={{marginTop:18,display:"flex",gap:14,flexWrap:"wrap",fontSize:13}}>{roots.map(r=><label key={r.id}><input type="checkbox" checked={r.enabled} onChange={e=>setRoots(a=>a.map(x=>x.id===r.id?{...x,enabled:e.target.checked}:x))}/> {r.label}</label>)}</div><p>{photo?`대표사진: ${photo.name}`:"대표사진을 선택하면 유사도 비교 기준으로 사용할 수 있습니다."}</p></section>
 {message&&<div style={{margin:"18px 0",padding:14,background:"#2e2824",color:"#fff",borderRadius:10}}>{message}</div>}
 {hits.length>0&&<><section style={{display:"flex",gap:18,flexWrap:"wrap",margin:"18px 0",fontSize:14}}><strong>총 {hits.length}장</strong><span>MYBOX {count("mybox")}</span><span>Google Drive {count("gdrive")}</span><span>PC {hits.length-count("mybox")-count("gdrive")}</span><span>완전 중복 {dup}</span><span>유사 이미지 {hits.filter(x=>x.match==="주변 이미지").length}</span><span>최종 보관 예상 {chosen.filter(x=>!x.duplicate).length}</span></section><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(250px,1fr))",gap:14}}>{hits.map(h=><article key={h.id} style={{border:"1px solid #e2d9d2",borderRadius:12,overflow:"hidden",background:"#fff"}}><img src={`/api/image-search/preview?path=${encodeURIComponent(h.path)}`} style={{width:"100%",aspectRatio:1,objectFit:"cover"}}/><div style={{padding:12,fontSize:13}}><label><input type="checkbox" checked={!!selected[h.id]} onChange={e=>setSelected(a=>({...a,[h.id]:e.target.checked}))}/> 보관 선택</label><strong style={{display:"block",marginTop:8}}>{h.fileName}</strong><div>{h.rootLabel}</div><div>{h.width&&h.height?`${h.width}×${h.height}`:"크기 확인 중"} · {(h.size/1024/1024).toFixed(2)}MB</div><div>{h.estimate} 추정 · {h.duplicate?"완전중복 검토":"고유 이미지"}</div><div>검색근거: {h.match}</div></div></article>)}</div><button disabled style={{marginTop:20,padding:12}}>승인 후 정리 실행 (DRY RUN 전용)</button></>}
 </main>
}
