import assert from "node:assert/strict";
import { mergeReprintItems, restoreReprintSession, type BarcodeSearchResult } from "../lib/wms/reprint-selection";
import { extractPrintedBarcodes } from "../lib/wms/barcode-photo-client";
const result = (n: number): BarcodeSearchResult => ({ purchaseOrderNumber: "140000001", skuId: String(n), barcode: `R${String(n).padStart(12, "0")}`, productName: "반지, 실버, 25호", optionName: "실버, 25호", fulfillmentCenter: "대구3", expectedDate: "2026-09-04" });
let items = mergeReprintItems([], [result(1), result(2)]);
items[0].quantity = 3;
items = mergeReprintItems(items, [result(2), result(3)]);
assert.equal(items.length, 3);
assert.equal(items[0].quantity, 3);
const unchecked = items.map(item => ({ ...item, checked: false }));
assert.equal(unchecked.length, 3, "전체해제는 목록을 삭제하지 않는다");
const restored = restoreReprintSession(JSON.stringify({ query: "90009", items: unchecked }));
assert.deepEqual(restored.items, unchecked);
assert.equal(restored.query, "90009");
assert.deepEqual(mergeReprintItems(unchecked, [result(1)]).map(item => item.checked), [true, false, false]);
assert.equal(restoreReprintSession(JSON.stringify([result(1)])).items[0].checked, true);
assert.deepEqual(restoreReprintSession('{"items":[null,{}]}').items, []);
assert.throws(() => mergeReprintItems([], Array.from({ length: 201 }, (_, i) => result(i))));
assert.equal(items[0].quantity, 3, "실패해도 기존 장수 유지");
assert.deepEqual(extractPrintedBarcodes("R203509890009\nR203509890009 R016220590020"), ["R203509890009", "R016220590020"]);
assert.deepEqual(extractPrintedBarcodes("01057695602 R20350989000 R2035098900099 R2O3509890009"), [], "자리 누락·OCR 오타를 임의 보정하지 않는다");
console.log("재출력 목록 검증 통과: 누적·중복·전체해제·장수·복원·200종 초과 차단");
