import assert from "node:assert/strict";
import { emptyPickingWaveStoreSnapshot, isPickingWaveStoreMutation } from "../lib/wms/picking-wave/shared-store-types";
import { applyPickingWaveStoreMutation } from "../lib/wms/picking-wave/server-store";
import { buildWorkCenterOverview, kstWorkDate } from "../lib/wms/work-center";
import { summarizeOutputGenerations } from "../lib/wms/output-generation-progress";
import type { PickingWave, PickingWaveItem, ShipmentOutputGeneration } from "../lib/wms/picking-wave/types";
import type { VendorOrderDraftLine } from "../lib/wms/vendor-order/types";
import { NextRequest } from "next/server";
import { POST as genericStorePost } from "../app/api/wms/picking-waves/route";

const stamp = "2026-09-02T00:00:00.000Z";
const wave: PickingWave = { id: "WAVE-20260902-926d76fa", status: "completed", sourcePurchaseOrderNumbers: ["PO1", "PO2", "PO3"], completedGroupIds: [], productDbConfigured: true, createdAt: stamp, updatedAt: stamp, shippingGroups: [{ key: "2026-09-04\u0000동탄1", expectedDate: "2026-09-04", fulfillmentCenter: "동탄1", purchaseOrderNumbers: ["PO1", "PO2", "PO3"] }] };
const item: PickingWaveItem = { id: "ITEM1", waveId: wave.id, productCode: "70000001", productName: "반지, 실버, 17호", barcode: "R123456789012", totalQuantity: 3, sources: wave.sourcePurchaseOrderNumbers.map(po => ({ purchaseOrderNumber: po, basketNumber: po, requestedQuantity: 1 })), locationStatus: "unlocated", modelSortKey: "m1", locationSortKey: "1", status: "full", pickedQuantity: 3, shortageQuantity: 0, allocations: [], createdAt: stamp, updatedAt: stamp };
const generation: ShipmentOutputGeneration = { generationId: "GEN-1", waveId: wave.id, purchaseOrderNumbers: ["PO1"], createdAt: stamp, updatedAt: stamp, expectedShippingGroupCount: 1, invoiceFileName: "invoice.xlsx", shipmentFileName: "shipment.xlsx", status: "shipment_generated" };
const snapshot = { ...emptyPickingWaveStoreSnapshot(), waves: [{ ...wave, outputGenerations: [generation] }], items: [item] };
const before = JSON.stringify(snapshot);
assert.equal(kstWorkDate(new Date("2026-09-03T15:00:00Z")), "2026-09-04");
assert.equal(kstWorkDate(new Date("2026-09-04T14:59:59Z")), "2026-09-04");
assert.equal(buildWorkCenterOverview(snapshot, new Date("2026-09-04T10:00:00Z")).works[0].delay, null);
const overview = buildWorkCenterOverview(snapshot, new Date("2026-09-05T00:00:00Z"));
assert.equal(overview.works.length, 1);
assert.equal(overview.works[0].state, null, "picking completed must not mean work completed");
assert.equal(overview.works[0].delay, "출고 유예 1일째");
assert.equal(overview.works[0].remainingShipmentPoCount, 2, "POs never included in a generation are still pending");
assert.match(overview.works[0].nextLabel, /남은 발주 2건/);
assert.ok(overview.works[0].nextHref.includes(wave.id));
assert.equal(summarizeOutputGenerations([generation], wave.sourcePurchaseOrderNumbers).pendingPurchaseOrders, 2);
assert.equal(buildWorkCenterOverview(snapshot, new Date("2030-01-01T00:00:00Z")).works.length, 1, "no date may hide a saved work");
assert.equal(JSON.stringify(snapshot), before, "read-only projection must not mutate source");

const archive = { action: "setOutboundWorkState" as const, waveId: wave.id, status: "archived" as const, expectedUpdatedAt: null, now: "2026-09-05T02:00:00Z" };
assert.ok(isPickingWaveStoreMutation(archive));
assert.ok(!isPickingWaveStoreMutation({ ...archive, status: "delete" }));
assert.ok(!isPickingWaveStoreMutation({ ...archive, now: "bad" }));
const archived = applyPickingWaveStoreMutation(snapshot, archive);
assert.deepEqual(archived.waves, snapshot.waves);
assert.deepEqual(archived.items, snapshot.items);
assert.deepEqual(archived.shipments, snapshot.shipments);
assert.deepEqual(archived.baskets, snapshot.baskets);
assert.deepEqual(archived.poConfirmationRecords, snapshot.poConfirmationRecords);
assert.deepEqual(archived.deletedWaveIds, {});
assert.equal(archived.outboundWorkStates?.[wave.id].history.length, 1);
assert.throws(() => applyPickingWaveStoreMutation(archived, archive), /다른 기기/);
const reopened = applyPickingWaveStoreMutation(archived, { ...archive, status: "active", expectedUpdatedAt: archive.now, now: "2026-09-05T02:01:00Z" });
assert.equal(reopened.outboundWorkStates?.[wave.id].status, "active");
assert.equal(reopened.outboundWorkStates?.[wave.id].history.length, 2);
assert.throws(() => applyPickingWaveStoreMutation(snapshot, { ...archive, status: "completed" }), /미처리/);
const oldSave = applyPickingWaveStoreMutation(archived, { action: "saveWave", wave: { ...wave, updatedAt: "2026-09-06T00:00:00Z" } });
assert.deepEqual(oldSave.outboundWorkStates, archived.outboundWorkStates, "legacy Wave saves must not undo explicit filing");
const full = { ...snapshot, waves: [{ ...wave, outputGenerations: [{ ...generation, purchaseOrderNumbers: wave.sourcePurchaseOrderNumbers, outputSetFileName: "set.zip", outputSetGeneratedAt: stamp }] }] };
assert.equal(buildWorkCenterOverview(full).works[0].canComplete, true);
assert.equal(applyPickingWaveStoreMutation(full, { ...archive, status: "completed" }).outboundWorkStates?.[wave.id].status, "completed");
assert.equal(buildWorkCenterOverview({ ...full, items: [{ ...item, status: "pending" }] }).works[0].canComplete, false);
const pending = { ...snapshot, waves: [{ ...wave, outputGenerations: [{ ...generation, status: "invoice_generated" as const }] }] };
assert.match(buildWorkCenterOverview(pending).works[0].nextHref, /\?generation=GEN-1/);
const overlapping = { ...snapshot, waves: [{ ...wave, outputGenerations: [{ ...generation, generationId: "OLD", status: "invoice_generated" as const, purchaseOrderNumbers: ["PO1", "PO2"] }, generation] }] };
assert.match(buildWorkCenterOverview(overlapping).works[0].nextLabel, /남은 발주 2건/, "partially superseded batches must not lead to an impossible duplicate Shipment");
const orphanLine = { id: "LINE", draftId: "DRAFT", waveId: wave.id, skuId: "70000001", vendorName: "거래처", shortageQuantity: 12, createdAt: stamp, updatedAt: stamp } as VendorOrderDraftLine;
assert.equal(buildWorkCenterOverview({ ...snapshot, vendorOrderLines: [orphanLine] }).pendingVendorSkuCount, 1, "use the same recovered draft projection as the vendor screen");
void genericStorePost(new NextRequest("http://localhost/api/wms/picking-waves", { method: "POST", body: JSON.stringify(archive), headers: { "Content-Type": "application/json" } })).then(response => {
  assert.equal(response.status, 403, "generic storage API must not bypass filing confirmation");
}).catch(error => { console.error(error); process.exitCode = 1; });
console.log("Work-center rules passed: KST date, full PO coverage, read-only projection, explicit filing, stale write blocked, all business data preserved");
