import assert from 'node:assert/strict';
import {splitShipmentOutputDocuments,validateInvoiceGroups} from '../lib/wms/shipment-output-split';
import {connectInvoiceGeneration} from '../lib/wms/invoice-generation';
import {matchesInvoiceTrackingGroups} from '../lib/wms/hanjin-shipment-auto';
import {summarizeOutputGenerations,chooseOutputGenerationId} from '../lib/wms/output-generation-progress';
import type {PurchaseOrderSourceDocument} from '../lib/wms/purchase-order-source/types';
import type {ShipmentOutputGeneration} from '../lib/wms/picking-wave/types';
const docs=(quantities:number[])=>quantities.map((orderedQuantity,i)=>({purchaseOrderNumber:String(100+i),records:[{orderedQuantity}]})) as PurchaseOrderSourceDocument[];
const daegu=splitShipmentOutputDocuments(docs([50,60,57,50]));assert.equal(daegu.length,1);assert.equal(daegu[0].totalQuantity,217);
const source=docs([100,80,70,60,55,45,40,35,25,20,15]);const before=JSON.stringify(source);const dongtan=splitShipmentOutputDocuments(source);
assert.equal(dongtan.length,3);assert.equal(dongtan.reduce((s,g)=>s+g.totalQuantity,0),545);assert(dongtan.every(g=>g.totalQuantity<=250&&g.documents.length>1));assert.equal(JSON.stringify(source),before);
const actual545=splitShipmentOutputDocuments(docs([80,65,60,55,50,50,45,40,35,35,30]));assert.equal(actual545.length,3);assert.equal(actual545.reduce((s,g)=>s+g.totalQuantity,0),545);assert(actual545.every(g=>g.documents.length>1));
const flat=dongtan.flatMap(g=>g.documents.map(d=>d.purchaseOrderNumber));assert.equal(new Set(flat).size,source.length);
const manualDocs=docs([90,80,70]);const destination=new Map(manualDocs.map(d=>[d.purchaseOrderNumber,'same']));
assert.deepEqual(validateInvoiceGroups([['100','102'],['101']],manualDocs,destination),[['100','102'],['101']]);
for(const plan of [[['100'],['101']], [['100','101'],['100','102']], [['100','101','999']]])assert.throws(()=>validateInvoiceGroups(plan,manualDocs,destination));
assert.throws(()=>validateInvoiceGroups([['100','101','102']],docs([100,100,60]),destination),/250/);
assert.throws(()=>validateInvoiceGroups([['100','101'],['102']],manualDocs,new Map([...destination,['101','different']])),/센터/);
const old:ShipmentOutputGeneration={generationId:'old',waveId:'W',purchaseOrderNumbers:['100','101','102'],invoiceFileName:'old.xlsx',invoiceGroups:[['100','101','102']],expectedShippingGroupCount:1,createdAt:'old',updatedAt:'old',status:'shipment_generated',shipmentFileName:'old-shipment.xlsx',outputSetFileName:'old.zip',outputSetGeneratedAt:'old'};
const incoming:ShipmentOutputGeneration={...old,generationId:'new',invoiceFileName:'new.xlsx',invoiceGroups:[['100','102'],['101']],status:'invoice_generated',shipmentFileName:undefined,outputSetGeneratedAt:undefined,outputSetFileName:undefined,updatedAt:'new'};
const original=JSON.stringify(old);const linked=connectInvoiceGeneration([old],incoming);assert.equal(JSON.stringify(old),original);assert.equal(linked.outputGenerations[0].shipmentFileName,'old-shipment.xlsx');assert.equal(linked.outputGenerations[0].supersededByGenerationId,'new');assert.equal(linked.generation.status,'invoice_generated');assert.equal(chooseOutputGenerationId(linked.outputGenerations,'new'),'new');assert.equal(summarizeOutputGenerations(linked.outputGenerations).pendingPurchaseOrders,3);
assert.throws(()=>connectInvoiceGeneration([old],{...incoming,purchaseOrderNumbers:['100']}),/일부/);
const reused=connectInvoiceGeneration(linked.outputGenerations,{...incoming,generationId:'unused'});assert.equal(reused.generation.generationId,'new');assert.equal(reused.outputGenerations.length,2);
const rows=(groups:string[][])=>groups.map((group,i)=>({trackingNumber:'TRACK'+i,fulfillmentCenter:'동탄1',kLabel:'동탄1 / 9월4일 / 발주서 번호 '+group.join(', ')}));
assert.equal(matchesInvoiceTrackingGroups(incoming.invoiceGroups,rows(incoming.invoiceGroups!)),true);assert.equal(matchesInvoiceTrackingGroups(incoming.invoiceGroups,rows(old.invoiceGroups!)),false);assert.equal(matchesInvoiceTrackingGroups(old.invoiceGroups,rows(incoming.invoiceGroups!)),false);
console.log('250 invoice grouping PASS: Daegu217=1, Dongtan545=3, whole PO balance, manual coverage/destination/limit guards, old records retained, exact new target, stale tracking rejected');
