import assert from "node:assert/strict";
import { emptyPickingWaveStoreSnapshot } from "../lib/wms/picking-wave/shared-store-types";
import { applyPickingWaveStoreMutation } from "../lib/wms/picking-wave/server-store";
import { packingGenerationKey, type PackingRow } from "../lib/wms/packing-progress";
import type { PickingWave, PickingWaveItem } from "../lib/wms/picking-wave/types";
const snapshot = emptyPickingWaveStoreSnapshot();
const wave = {id:"PACK-TEST",status:"order_confirmed",sourcePurchaseOrderNumbers:["140000001","140000002"],outputGenerations:[{generationId:"GEN1",purchaseOrderNumbers:["140000001","140000002"],status:"shipment_generated",shipmentFileName:"fixture.xlsx",outputSetFileName:"fixture.zip",outputSetGeneratedAt:"2026-09-06",invoiceGroups:[["140000001"],["140000002"]]}]} as PickingWave;
const item = {id:"I1",waveId:wave.id,productCode:"12345678",barcode:"R12345678",status:"full",pickedQuantity:3,totalQuantity:3,shortageQuantity:0,sources:wave.sourcePurchaseOrderNumbers.map((po,i)=>({purchaseOrderNumber:po,basketNumber:String(i),requestedQuantity:i+1})),allocations:wave.sourcePurchaseOrderNumbers.map((po,i)=>({purchaseOrderNumber:po,basketNumber:String(i),requestedQuantity:i+1,fulfilledQuantity:i+1,shortageQuantity:0}))} as PickingWaveItem;
snapshot.waves=[wave]; snapshot.items=[item];
const rows: PackingRow[]=wave.sourcePurchaseOrderNumbers.map((po,i)=>({key:`K${i}`,shipmentNumber:`5000000${i}`,purchaseOrderNumber:po,skuId:item.productCode,barcode:item.barcode,quantity:i+1}));
const mutation={action:"savePackingProgress" as const,waveId:wave.id,generationKey:packingGenerationKey(wave),rows,checkedKeys:["K0"],expectedUpdatedAt:null,dispatched:false,now:"2026-09-06T01:00:00Z"};
const reprinted=structuredClone(wave);reprinted.outputGenerations![0].outputSetGeneratedAt="2026-09-07";
assert.equal(packingGenerationKey(reprinted),packingGenerationKey(wave),"Identical output reprints preserve packing checks");
const first=applyPickingWaveStoreMutation(snapshot,mutation);
assert.deepEqual(first.items,snapshot.items);assert.deepEqual(first.waves,snapshot.waves);assert.equal(first.packingProgress![wave.id].checkedKeys.length,1);
assert.throws(()=>applyPickingWaveStoreMutation(first,mutation),/다른 기기/);
assert.throws(()=>applyPickingWaveStoreMutation(snapshot,{...mutation,dispatched:true}),/모든 상품/);
const firstGenerationOnly=applyPickingWaveStoreMutation(snapshot,{...mutation,rows:[rows[0]],checkedKeys:[]});
assert.equal(firstGenerationOnly.packingProgress![wave.id].rows.length,1,"a selected Shipment generation may be checked without requiring the whole wave");
assert.throws(()=>applyPickingWaveStoreMutation(snapshot,{...mutation,rows:[rows[0],rows[0]]}),/중복/);
assert.throws(()=>applyPickingWaveStoreMutation(snapshot,{...mutation,rows:rows.map(r=>({...r,barcode:"BAD"}))}),/바코드/);
assert.throws(()=>applyPickingWaveStoreMutation(snapshot,{...mutation,generationKey:"stale"}),/변경/);
assert.throws(()=>applyPickingWaveStoreMutation(snapshot,{...mutation,checkedKeys:["unknown"]}),/체크 대상/);
const changed=structuredClone(first);changed.waves[0].outputGenerations![0].shipmentFileName="changed.xlsx";
assert.throws(()=>applyPickingWaveStoreMutation(changed,{...mutation,generationKey:packingGenerationKey(changed.waves[0]),expectedUpdatedAt:mutation.now}),/처음부터/);
const final=applyPickingWaveStoreMutation(first,{...mutation,checkedKeys:["K0","K1"],expectedUpdatedAt:mutation.now,dispatched:true,now:"2026-09-06T02:00:00Z"});
assert.equal(final.outboundWorkStates![wave.id].status,"completed");assert.ok(final.packingProgress![wave.id].dispatchedAt);
assert.deepEqual(final.packingProgress![wave.id].dispatchedShipmentNumbers,["50000000","50000001"]);
const firstShipmentDone=applyPickingWaveStoreMutation(first,{...mutation,checkedKeys:["K0"],dispatchedShipmentNumbers:["50000000"],expectedUpdatedAt:mutation.now,now:"2026-09-06T01:30:00Z"});
assert.deepEqual(firstShipmentDone.packingProgress![wave.id].dispatchedShipmentNumbers,["50000000"]);
const secondShipmentDoneWithoutChecks=applyPickingWaveStoreMutation(first,{...mutation,dispatchedShipmentNumbers:["50000001"],expectedUpdatedAt:mutation.now,now:"2026-09-06T01:31:00Z"});
assert.deepEqual(secondShipmentDoneWithoutChecks.packingProgress![wave.id].dispatchedShipmentNumbers,["50000001"],"shipment dispatch status is independent from optional item checks");
const otherCenterRows=[{...rows[0],key:"OTHER",shipmentNumber:"50000002"}];
const preservedAcrossCenters=applyPickingWaveStoreMutation(firstShipmentDone,{...mutation,rows:otherCenterRows,checkedKeys:[],dispatchedShipmentNumbers:["50000000","50000002"],expectedUpdatedAt:"2026-09-06T01:30:00Z",now:"2026-09-06T01:40:00Z"});
assert.deepEqual(preservedAcrossCenters.packingProgress![wave.id].dispatchedShipmentNumbers,["50000000","50000002"],"completed Shipment status must survive switching centers");
assert.deepEqual(final.items,snapshot.items);assert.deepEqual(final.waves,snapshot.waves);
const reopened=applyPickingWaveStoreMutation(final,{...mutation,dispatchedShipmentNumbers:["50000001"],expectedUpdatedAt:"2026-09-06T02:00:00Z",now:"2026-09-06T03:00:00Z"});
assert.deepEqual(reopened.packingProgress![wave.id].dispatchedShipmentNumbers,["50000001"]);assert.equal(reopened.packingProgress![wave.id].dispatchedAt,undefined);
console.log("Packing PASS: multi-center SKU, bulk and reversible dispatch, separate persistent checks, stale conflict, full coverage, quantities, barcode, original records unchanged");
