import assert from "node:assert/strict";
import { emptyPickingWaveStoreSnapshot } from "../lib/wms/picking-wave/shared-store-types";
import { buildWorkCenterOverview } from "../lib/wms/work-center";
import { packingGenerationKey } from "../lib/wms/packing-progress";
import type { PickingWave, PickingWaveItem, ShipmentOutputGeneration } from "../lib/wms/picking-wave/types";

const stamp = "2026-09-08T01:00:00.000Z";
const pos = ["139100001", "139100002", "139100003"];
const target: PickingWave = { id: "TARGET", status: "completed", sourcePurchaseOrderNumbers: pos, completedGroupIds: [], productDbConfigured: true, createdAt: stamp, updatedAt: stamp, shippingGroups: pos.map((po, index) => ({ key: `${index}`, expectedDate: `2026-09-${10 + index}`, fulfillmentCenter: `센터${index + 1}`, purchaseOrderNumbers: [po] })) };
target.outputGenerations = pos.map((po, index) => ({ generationId: `GEN-${index + 1}`, waveId: target.id, purchaseOrderNumbers: [po], createdAt: stamp, updatedAt: stamp, expectedShippingGroupCount: 1, invoiceFileName: `invoice-${index}.xlsx`, shipmentFileName: `shipment-${index}.xlsx`, outputSetGeneratedAt: stamp, outputSetFileName: `set-${index}.zip`, status: "shipment_generated" } satisfies ShipmentOutputGeneration));
target.selectedOutputGenerationId = "GEN-3";
const sources = pos.map((po, index) => ({ purchaseOrderNumber: po, basketNumber: po, requestedQuantity: index + 2, shippingGroupKey: `2026-09-${10 + index}\u0000센터${index + 1}` }));
const item: PickingWaveItem = { id: "TARGET::SKU", waveId: target.id, productCode: "12345678", productName: "공유 SKU", barcode: "R123", totalQuantity: 9, sources, status: "full", pickedQuantity: 9, shortageQuantity: 0, allocations: sources.map(source => ({ ...source, fulfilledQuantity: source.requestedQuantity, shortageQuantity: 0 })), locationStatus: "unlocated", modelSortKey: "m", locationSortKey: "m", createdAt: stamp, updatedAt: stamp };
const owner: PickingWave = { ...target, id: "OWNER", sourcePurchaseOrderNumbers: [pos[0], pos[2]], outputGenerations: [], selectedOutputGenerationId: undefined };
const ownerItem: PickingWaveItem = { ...item, id:"OWNER::SKU", waveId:owner.id, sources:sources.filter(source=>owner.sourcePurchaseOrderNumbers.includes(source.purchaseOrderNumber)), allocations:item.allocations.filter(row=>owner.sourcePurchaseOrderNumbers.includes(row.purchaseOrderNumber)), totalQuantity:6, pickedQuantity:6 };
const snapshot = { ...emptyPickingWaveStoreSnapshot(), waves: [target, owner], items: [item,ownerItem], outboundWorkStates: { OWNER: { status: "completed" as const, source: "manual" as const, updatedAt: stamp, history: [] } }, packingProgress: { TARGET: { generationKey: packingGenerationKey(target), manifestKey: "manifest", rows: pos.map((po, index) => ({ key: `ROW-${index}`, shipmentNumber: `5000000${index + 1}`, purchaseOrderNumber: po, skuId: item.productCode, barcode: item.barcode, quantity: index + 2 })), checkedKeys: ["ROW-1"], updatedAt: stamp } } };
const before = JSON.stringify(snapshot);
const summary = buildWorkCenterOverview(snapshot).works.find(work => work.id === target.id)!;
assert.equal(summary.purchaseOrderCount, 1);
assert.equal(summary.skuCount, 1, "A SKU shared with a pending PO remains visible");
assert.equal(summary.totalQuantity, 3, "Completed PO quantities are removed without dropping the shared SKU");
assert.equal(summary.centerCount, 1);
assert.deepEqual(summary.expectedDates, ["2026-09-11"]);
assert.deepEqual(summary.shippingByDate, [{ expectedDate: "2026-09-11", centers: [{ fulfillmentCenter: "센터2", totalQuantity: 3 }] }]);
assert.equal(summary.remainingShipmentPoCount, 0); assert.equal(summary.remainingOutputPoCount, 0);
assert.equal(summary.packingTargets.length, 1);
assert.match(summary.packingTargets[0].label, /센터2.*Shipment 1개 · 총 3개/);
assert.match(summary.packingTargets[0].href, /GEN-2/);
assert.doesNotMatch(summary.packingTargets[0].href, /GEN-1|GEN-3/);
assert.match(summary.packingLabel || "", /센터2.*\(1\/1\)/, "Original generation key keeps valid packing checks available after projection");
assert.equal(summary.completedAt, null, "Partial overlap never invents completion");
assert.equal(JSON.stringify(snapshot), before, "Display projection preserves every source and generation");

const full = structuredClone(snapshot); full.waves[1].sourcePurchaseOrderNumbers = [...pos]; full.items[1] = { ...item, id:ownerItem.id, waveId:owner.id };
const hidden = buildWorkCenterOverview(full).works.find(work => work.id === target.id)!;
assert.equal(hidden.fullyCompletedElsewhere, true);
assert.equal(hidden.purchaseOrderCount, 3, "The folded historical card keeps original work scope");
assert.equal(hidden.canComplete, false); assert.equal(hidden.delay, null); assert.deepEqual(hidden.packingTargets, []);

const reopened = structuredClone(snapshot);
reopened.outboundWorkStates.OWNER = { status: "active", source: "manual", updatedAt: "2026-09-08T02:00:00.000Z", history: [] } as never;
const restored = buildWorkCenterOverview(reopened).works.find(work => work.id === target.id)!;
assert.equal(restored.purchaseOrderCount, 3); assert.equal(restored.totalQuantity, 9);
const onlyPicked = structuredClone(snapshot); delete (onlyPicked as { outboundWorkStates?: unknown }).outboundWorkStates;
assert.equal(buildWorkCenterOverview(onlyPicked).works.find(work => work.id === target.id)!.purchaseOrderCount, 3, "Picking completion and generated documents alone are not dispatch evidence");
const filedOwner = buildWorkCenterOverview(snapshot).works.find(work => work.id === owner.id)!;
assert.equal(filedOwner.completedAt, stamp); assert.equal(filedOwner.purchaseOrderCount, 2, "The work that recorded dispatch keeps its own historical scope");
const mixed = structuredClone(snapshot);
mixed.waves[0].outputGenerations = [{ ...target.outputGenerations![0], generationId: "MIXED", purchaseOrderNumbers: [pos[0],pos[1]], expectedShippingGroupCount: 2 }];
mixed.waves[0].selectedOutputGenerationId="MIXED";mixed.waves[0].shipmentDocumentsCompletedAt=stamp;
const mixedSummary=buildWorkCenterOverview(mixed).works.find(work=>work.id===target.id)!;
assert.equal(mixedSummary.remainingShipmentPoCount,1);assert.equal(mixedSummary.remainingOutputPoCount,1);
assert.deepEqual(mixedSummary.packingTargets,[]);assert.equal(mixedSummary.packingHref,null);
assert.match(mixedSummary.nextLabel,/남은 발주 1건/);assert.match(mixedSummary.nextHref,/#hanjin-step-1$/);
assert.deepEqual(mixed.waves[0].outputGenerations[0].purchaseOrderNumbers,[pos[0],pos[1]],"Mixed physical document keeps original PO membership");
mixed.waves[0].outputGenerations[0].status="invoice_generated";
assert.match(buildWorkCenterOverview(mixed).works.find(work=>work.id===target.id)!.nextHref,/#hanjin-step-1$/,"Incomplete mixed batches also restart with remaining POs only");
console.log("PASS cross-wave summary: exact remaining POs, shared SKU quantities, center/date/packing targets, original generation checks, all-complete filing, restoration, no false dispatch, immutable source.");
